export const brokers = [
  {
    id: 'robinhood',
    name: 'Robinhood',
    short: 'RH',
    description: 'Agentic Trading account via Robinhood Trading MCP.',
    connection: 'Agentic MCP',
    status: 'paper-locked',
    badge: 'Live-only path',
    note: 'Visible for planning, but locked in SignalForge while this deployment remains paper-only.',
  },
  {
    id: 'alpaca',
    name: 'Alpaca',
    short: 'A',
    description: 'Developer-first brokerage with OAuth and a dedicated paper-trading environment.',
    connection: 'OAuth 2.0',
    status: 'available',
    badge: 'Connect now',
    note: 'Preferred SignalForge paper broker.',
  },
  {
    id: 'ibkr',
    name: 'Interactive Brokers',
    short: 'IB',
    description: 'Web API with trading features and third-party authorization paths.',
    connection: 'Web API / OAuth',
    status: 'planned',
    badge: 'Coming soon',
    note: 'Third-party integrations can require broker approval.',
  },
  {
    id: 'schwab',
    name: 'Charles Schwab',
    short: 'CS',
    description: 'Brokerage account and trading API integration candidate.',
    connection: 'Trader API',
    status: 'planned',
    badge: 'Coming soon',
    note: 'Requires an approved developer application before enabling users.',
  },
  {
    id: 'etrade',
    name: 'E*TRADE',
    short: 'ET',
    description: 'Developer platform with OAuth authorization and sandbox support.',
    connection: 'OAuth 1.0a',
    status: 'planned',
    badge: 'Coming soon',
    note: 'Sandbox support makes it suitable for a later paper-safe integration.',
  },
  {
    id: 'tradestation',
    name: 'TradeStation',
    short: 'TS',
    description: 'Trading API integration candidate for brokerage account automation.',
    connection: 'Trading API',
    status: 'planned',
    badge: 'Coming soon',
    note: 'Enable only after the app is registered for the appropriate API access.',
  },
  {
    id: 'tastytrade',
    name: 'tastytrade',
    short: 'TT',
    description: 'Open API with OAuth2, orders, positions, market data and sandbox workflows.',
    connection: 'OAuth 2.0',
    status: 'planned',
    badge: 'Coming soon',
    note: 'Good candidate for a future paper/sandbox connection.',
  },
  {
    id: 'tradier',
    name: 'Tradier',
    short: 'TR',
    description: 'Brokerage API with OAuth2 and a dedicated paper-trading sandbox.',
    connection: 'OAuth 2.0',
    status: 'planned',
    badge: 'Coming soon',
    note: 'Public apps require Tradier partner access.',
  },
  {
    id: 'webull',
    name: 'Webull',
    short: 'WB',
    description: 'OpenAPI plus Connect API for third-party account authorization and trading.',
    connection: 'OAuth 2.0',
    status: 'planned',
    badge: 'Coming soon',
    note: 'Third-party Connect API onboarding is required before activation.',
  },
  {
    id: 'public',
    name: 'Public',
    short: 'P',
    description: 'Trading API with account data and order placement capabilities.',
    connection: 'Trading API',
    status: 'planned',
    badge: 'Coming soon',
    note: 'A production multi-user integration needs the appropriate commercial authorization model.',
  },
];

export function brokerById(id) {
  return brokers.find((broker) => broker.id === id) || null;
}
